batch_size: 1024
height: 32
learning_rate: 0.0001
max_text_length: 23
model_path: Models/1_image_to_word\202404151833
train_epochs: 100
train_workers: 20
vocab: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
width: 128
